//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.18449
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace It.Uniba.Di.Cdg.SocialTfs.ServiceLibrary.Linkedin {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class LinkedInUri : global::System.Configuration.ApplicationSettingsBase {
        
        private static LinkedInUri defaultInstance = ((LinkedInUri)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new LinkedInUri())));
        
        public static LinkedInUri Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/v1/people/~:(id,picture-url)?format=json")]
        public string VERIFY_CREDENTIALS {
            get {
                return ((string)(this["VERIFY_CREDENTIALS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/v1/people/~:(skills)?format=json")]
        public string SKILLS {
            get {
                return ((string)(this["SKILLS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/v1/people/~/connections?format=json")]
        public string FRIENDS {
            get {
                return ((string)(this["FRIENDS"]));
            }
        }
    }
}
